# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0002_auto_20170716_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
